require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

IS_CI = ENV['APPCENTER_BUILD_ID']

# Define find-and-replace function
# def find_and_replace(dir, findstr, replacestr)
#  Dir[dir].each do |name|
#      text = File.read(name)
#      replace = text.gsub(findstr,replacestr)
#      replaced = text.index(replacestr)
#      if replaced == nil && text != replace
#          puts "Fix: " + name
#          File.open(name, "w") { |file| file.puts replace }
#          STDOUT.flush
#      end
#  end
#  Dir[dir + '*/'].each(&method(:find_and_replace))
#end

target 'mybattle11' do
	config = use_native_modules!

	# Flags change depending on the env values.s
	flags = get_default_flags()

	use_react_native!(
		:path => config[:reactNativePath],
		# to enable hermes on iOS, change `false` to `true` and then install pods
		:hermes_enabled => true,
		:fabric_enabled => flags[:fabric_enabled],
		# An absolute path to your application root.
		:app_path => "#{Pod::Config.instance.installation_root}/.."
	)

	 permissions_path = '../node_modules/react-native-permissions/ios'
	pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
	use_native_modules!

	pod 'Firebase', :modular_headers => true
	pod 'FirebaseCoreInternal', :modular_headers => true
	pod 'GoogleUtilities', :modular_headers => true
	pod 'FirebaseCore', :modular_headers => true
	pod 'GoogleSignIn', '~> 7.0.0'
  
	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	if not IS_CI
		use_flipper!({ 'Flipper' => '0.162.0' })

	end
	post_install do |installer|
		react_native_post_install(installer)
		installer.pods_project.targets.each do |target|

			if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
				target.build_configurations.each do |config|
					config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
				end
			end
		end
		# # to build for the simulator on Apple M1
		# installer.pods_project.targets.each do |target|
		#   target.build_configurations.each do |config|
		#     # disables arm64 builds for the simulator
		#     config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
		#   end
		# end

		#find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
		#"atomic_notify_one(state)", "folly::atomic_notify_one(state)")

		#find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
		#"atomic_wait_until(&state, previous | data, deadline)", "folly::atomic_wait_until(&state, previous | data, deadline)")

		installer.pods_project.build_configurations.each do |config|
			if config.name == 'Release'
				config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
			end
		end
	end
end
