require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mybattle11' do
	config = use_native_modules!

	# Flags change depending on the env values.s
	flags = get_default_flags()

	use_react_native!(
		:path => config[:reactNativePath],
		# Hermes is now enabled by default. Disable by setting this flag to false.
		:hermes_enabled => flags[:hermes_enabled],
		:fabric_enabled => flags[:fabric_enabled],
		# Enables Flipper.
		#
		# Note that if you have use_frameworks! enabled, Flipper will not work and
		# you should disable the next line.
		:flipper_configuration => flipper_config,
		# An absolute path to your application root.
		:app_path => "#{Pod::Config.instance.installation_root}/.."
	)

	 permissions_path = '../node_modules/react-native-permissions/ios'
	pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
	use_native_modules!

	pod 'Firebase', :modular_headers => true
	pod 'FirebaseCoreInternal', :modular_headers => true
	pod 'GoogleUtilities', :modular_headers => true
	pod 'FirebaseCore', :modular_headers => true
	pod 'GoogleSignIn', '~> 7.0.0'
  
	post_install do |installer|
		# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
		react_native_post_install(
			installer,
			config[:reactNativePath],
			:mac_catalyst_enabled => false
		)
		
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
				
				# Fix for Xcode 15 and arm64 architecture
				config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
				
				# Additional build settings for M1 compatibility
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
			end
		end
	end
end
