export const AUTHSTACK = 'AUTHSTACK';
export const AUTH_LOADING_SCREEN = 'AUTH_LOADING_SCREEN';
export const CREATE_CONTEST = 'CREATE_CONTEST';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const REFERRAL_SCREEN = 'REFERRAL_SCREEN';
export const MY_CONTEST = 'MY-CONTEST';
export const ALL_CONTEST_LIST = 'ALL-CONTEST-LIST';
export const SELECT_CAPTAIN = 'SELECT-CAPTAIN';
export const LEADERBOARD = 'LEADERBOARD';
export const TRANSACTION_SCREEN = 'TRANSACTION_SCREEN';
export const WITHDRAW_SCREEN = 'WITHDRAW_SCREEN';
export const VERIFY_ADHAAR_SCREEN = 'VERIFY_ADHAAR_SCREEN';
export const VERIFY_UPI = 'VERIFY_UPI';
export const VERIFY_DL = 'VERIFY_DL';
export const VERIFY_VOTER_ID = 'VERIFY_VOTER_ID';
export const OTHER_USER_PROFILE = ' OTHER_USER_PROFILE';
export const WEB_URL = ' WEB_URL';
export const TDS_REPORT = ' TDS_REPORT';
export const DESK_HELP = ' DESK_HELP';
export const MATCH_CARD_MYCONTEST = ' MATCH_CARD_MYCONTEST';
export const SELECT_SUBSTITUTE = ' SELECT_SUBSTITUTE';
export const SHARE_TEAM = ' SHARE_TEAM';
export const CONTESTSHARE = ' CONTESTSHARE';
export const PRIVATECONTESTLEADER = ' PRIVATECONTESTLEADER';
export const ADDCASH_VERIFICATION = ' ADDCASH_VERIFICATION';
export const UPLOAD_AADHAR = ' UPLOAD_AADHAR';
export const HOME_PRIVACY = ' HOME_PRIVACY';

export const Filter_Sheet = 'Filter_Sheet';
export const OTP = 'OTP';
export const CRICKET_MATCHES = 'CRICKET_MATCHES';
export const LOGIN = 'LOGIN';
export const Notification__SCREEN = 'Notification__SCREEN';
export const Common_Tabs = 'Common_Tabs';
export const Match_Remainder = 'Match_Remainder';
export const CONTEST_LEADERBORD = 'CONTEST_LEADERBORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const NFT_SCREEN1 = 'NFT_SCREEN1';
export const HOME_SCREEN = 'HOME_SCREEN';
export const RENTED_SCREEN = 'RENTED_SCREEN';
export const PURCHASE_SCREEN = 'PURCHASE_SCREEN';
export const VERIFY_EMAIL_SCREEN = 'VERIFY_EMAIL_SCREEN';
export const VERIFY_EMAIL_OTP_SCREEN = 'VERIFY_EMAIL_OTP_SCREEN';
export const VERIFY_PAN_SCREEN = 'VERIFY_PAN_SCREEN';
export const VERIFY_BANK_SCREEN = 'VERIFY_BANK_SCREEN';
export const ADD_CARD_SCREEN = 'ADD_CARD_SCREEN';
export const ADD_MONEY_SCREEN = 'ADD_MONEY_SCREEN';
export const RENTED_FLATLIST = 'RENTED_FLATLIST';
export const PURCHASED_FLATLIST = 'PURCHASED_FLATLIST';
export const Single_Ipl_Card = 'Single_Ipl_Card';
export const PRACTISE_SCREEN = 'PRACTISE_SCREEN';
export const Top_Slider_FlatList = 'Top_Slider_FlatList';
export const NFC = 'NFC';
export const PROFILE = 'PROFILE_SCREEN';
export const REFER_EARN = ' REFER_EARN';
export const PROFILE_EDIT = 'EDIT_PROFILE_SCREEN';
export const MY_BALANCE = 'MY_BALANCE';
export const HOME = 'HOME';
export const CONTEST = 'CONTEST';
export const BOTTOM_NAVIGATION_STACK = 'BOTTOM_NAVIGATION_STACK';
export const BOTTOM_TAB_HOMESCREEN = 'BOTTOM_TAB_HOMESCREEN';
export const BOTTOM_TAB_MESSAGE_SCREEN = 'BOTTOM_TAB_MESSAGE_SCREEN';
export const BOTTOM_TAB_ADDMORE_SCREEN = 'BOTTOM_TAB_ADDMORE_SCREEN';
export const BOTTOM_TAB_USERPROFILE_SCREEN = 'BOTTOM_TAB_USERPROFILE_SCREEN';
export const BOTTOM_TAB_MENU_SCREEN = 'BOTTOM_TAB_MENU_SCREEN';
export const BOTTOM_TAB_CONTEST_SCREEN = 'BOTTOM_TAB_CONTEST_SCREEN';
export const BOTTOM_TAB_PROFILE_SCREEN = 'BOTTOM_TAB_PROFILE_SCREEN';
export const BOTTOM_TAB_MORE_SCREEN = 'BOTTOM_TAB_MORE_SCREEN';
export const HOME_SCREEN_MAIN = 'HOME_SCREEN_MAIN';
export const CONTEST_SCREEN_MAIN = 'CONTEST_SCREEN_MAIN';
export const PROFILE_SCREEN_MAIN = 'PROFILE_SCREEN_MAIN';
export const MORE_SCREEN_MAIN = 'MORE_SCREEN_MAIN';
export const MANAGE_PAYMENTS_SCREEN = 'MANAGE_PAYMENTS_SCREEN';
export const KYC_SCREEN = 'KYC_SCREEN';
export const PLAYER_PREVIEW = 'PLAYER-PREVIEW';
export const PLAYER_PREVIEW_TWO = 'PLAYER_PREVIEW_TWO';
export const SELECT_PLAYER = 'SELECT-PLAYER';
export const MYBATTLELOGIN = 'MYBATTLELOGIN';
export const MYBATTLEOTP = 'MYBATTLEOTP';
export const MYBATTLEREFEREARN = 'MYBATTLEREFEREARN';
export const UPLOAD_SELFIE = 'UPLOAD_SELFIE';
export const MY_CONTEST_SWPIE = 'MY_CONTEST_SWPIE';
export const PAYMENT_SCREEN  = 'PAYMENT_SCREEN';
export const LUDO_GAME_MODE='LudoGameMode'
export const LUDO_HOW_TO_PLAY='LudoHowToPlay'
export const RUMMY_GAME_MODE='RummyGameMode'

export const GAME_TABLE='GameTable'
export const GAME_JOIN_TABLE='GameJoinTable'
export const GAME_WEB_VIEW='GameWebView'

export const CRICKET_TAB = 'CRICKET_TAB';

// Scoreboard routes
export const SCOREBOARD_CREATE = 'Scoreboard/Create';
export const SCOREBOARD_LIST = 'Scoreboard/List';
export const SCOREBOARD_DETAILS = 'Scoreboard/Details';
export const SCOREBOARD_MATCH = 'Scoreboard/Match';



