const {img1, img2, img3, img4, img5, img6} = require('./helper/image');
const {
  img7,
  img8,
  img9,
  img10,
  Badge,
  Cup,
  Ellipse,
  Dollar,
  CheckMark,
} = require('./helper/image');
import Swipper from './common/Swipper/Swipper';
// const swipper = Swipper;

const DATA = [
  {
    id: 1,
    img: img1,
    title: 'God Watching',
    amount: '$23',
  },
  {
    id: 2,
    img: img2,
    title: 'God Watching',
    amount: '$24',
  },
  {
    id: 3,
    img: img3,
    title: 'God Watching',
    amount: '$25',
  },
  {
    id: 4,
    img: img4,
    title: 'God Watching',
    amount: '$26',
  },
  {
    id: 5,
    img: img5,
    title: 'God Watching',
    amount: '$27',
  },
  {
    id: 6,
    img: img6,
    title: 'God Watching',
    amount: '$28',
  },
];

export default DATA;

export const RENTED_DATA = [
  {
    id: 1,
    img: img7,
    title: 'God Watching',
    daysLeft: '5 days left',
    commission: 'Commission',
    owner: 'Owner (John Wick)',
    rentee: 'Rentee(Nomadicstar)',
    commisionPercentage: '0.5%',
    renteePercentage: '0.5%',
    amount: '$25',
  },
  {
    id: 2,
    img: img8,
    title: 'God Watching',
    daysLeft: '5 days left',
    commission: 'Commission',
    owner: 'Owner (John Wick)',
    rentee: 'Rentee(Nomadicstar)',
    commisionPercentage: '0.5%',
    renteePercentage: '0.5%',
    amount: '$25',
  },
  {
    id: 3,
    img: img9,
    title: 'God Watching',
    daysLeft: '5 days left',
    commission: 'Commission',
    owner: 'Owner (John Wick)',
    rentee: 'Rentee(Nomadicstar)',
    commisionPercentage: '0.5%',
    renteePercentage: '0.5%',
    amount: '$25',
  },
  {
    id: 4,
    img: img10,
    title: 'God Watching',
    daysLeft: '5 days left',
    commission: 'Commission',
    owner: 'Owner (John Wick)',
    rentee: 'Rentee(Nomadicstar)',
    commisionPercentage: '0.5%',
    renteePercentage: '0.5%',
    amount: '$25',
  },
];

// Swipper
export const mySwipper = [
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
  {
    swipper: <Swipper />,
  },
];

export const contestCommonCardData = [
  {
    id: 1,
    prizePool: 'PRIZE POOL',
    multiple: 'Multiple Entries',
    amount: '₹11,00',
    winnerDiscount: '60% Winners l 1st ₹1,100',
    rupee: '₹50',
    noOfSpot: '10,000 spots',
    leftSpot: '3,857 spots left',
    Badge: Badge,
    Cup: Cup,
    Ellipse: Ellipse,
    Dollar: Dollar,
    CheckMark: CheckMark,
    badgeAmount: '₹100',
    cupPercentage: '50%',
    playStatus: 'Single',
  },
  {
    id: 2,
    prizePool: 'PRIZE POOL',
    multiple: 'Multiple Entries',
    amount: '₹11,00',
    winnerDiscount: '60% Winners l 1st ₹1,100',
    rupee: '₹50',
    noOfSpot: '10,000 spots',
    leftSpot: '3,857 spots left',
    Badge: Badge,
    Cup: Cup,
    Ellipse: Ellipse,
    Dollar: Dollar,
    CheckMark: CheckMark,
    badgeAmount: '₹100',
    cupPercentage: '50%',
    playStatus: 'Single',
  },
  {
    id: 3,
    prizePool: 'PRIZE POOL',
    multiple: 'Multiple Entries',
    amount: '₹11,00',
    winnerDiscount: '60% Winners l 1st ₹1,100',
    rupee: '₹50',
    noOfSpot: '10,000 spots',
    leftSpot: '3,857 spots left',
    Badge: Badge,
    Cup: Cup,
    Ellipse: Ellipse,
    Dollar: Dollar,
    CheckMark: CheckMark,
    badgeAmount: '₹100',
    cupPercentage: '50%',
    playStatus: 'Single',
  },
];

export const practiceCommonCardData = [
  {
    id: 1,
    PracticeContest: 'Practice Contest',
    join: 'Join',
    noOfSpot: '2 spots',
    gloryAwait: 'Glory awaits!',
    leftSpot: '1 spots left',
    Badge: Badge,
    Ellipse: Ellipse,
    Dollar: Dollar,
    playStatus: 'Single',
  },

  {
    id: 2,
    PracticeContest: 'Practice Contest',
    join: 'Join',
    noOfSpot: '2 spots',
    gloryAwait: 'Glory awaits!',
    leftSpot: '1 spots left',
    Badge: Badge,
    Ellipse: Ellipse,
    Dollar: Dollar,
    playStatus: 'Single',
  },
  {
    id: 3,

    PracticeContest: 'Practice Contest',
    join: 'Join',
    noOfSpot: '2 spots',
    gloryAwait: 'Glory awaits!',
    leftSpot: '1 spots left',
    Badge: Badge,
    Ellipse: Ellipse,
    Dollar: Dollar,
    playStatus: 'Single',
  },
];

export const TransactionData = [
  {
    id: '1',
    type: 'deposit_request_pending',
    title: 'Deposit',
    date: '13-06-25 12:48 PM',
    amount: '+ 10.00',
    status: 'Pending',
  },
  {
    id: '2',
    type: 'fee',
    title: 'Fee',
    date: '20-04-25 02:22 PM',
    amount: '- 5.00',
    status: 'Approved',
  },
  {
    id: '3',
    type: 'fee',
    title: 'Fee',
    date: '10-04-25 01:10 PM',
    amount: '- 2.00',
    status: 'Approved',
  },
  {
    id: '4',
    type: 'deposit_request_failed',
    title: 'Deposit',
    date: '13-06-25 12:48 PM',
    amount: '+ 10.00',
    status: 'Failed',
  },
  {
    id: '5',
    type: 'prize',
    title: 'Prize',
    date: '13-06-25 12:48 PM',
    amount: '+ 50.00',
    status: 'Approved',
  },
  {
    id: '6',
    type: 'prize',
    title: 'Prize',
    date: '14-04-25 10:36 AM',
    amount: '+ 1.00',
    status: 'Approved',
  },
  {
    id: '7',
    type: 'prize',
    title: 'Prize',
    date: '12-04-25 01:59 PM',
    amount: '+ 1.00',
    status: 'Approved',
  },
   {
    id: '8',
    type: 'prize',
    title: 'Prize',
    date: '12-04-25 12:55 PM',
    amount: '+ 1.00',
    status: 'Approved',
  },
  {
    id: '9',
    type: 'fee',
    title: 'Fee',
    date: '08-04-25 12:48 AM',
    amount: '- 4.00',
    status: 'Approved',
  },
  {
    id: '10',
    type: 'fee',
    title: 'Fee',
    date: '08-04-25 12:44 AM',
    amount: '- 4.00',
    status: 'Approved',
  },
  {
    id: '11',
    type: 'fee',
    title: 'Fee',
    date: '08-04-25 12:37 AM',
    amount: '- 4.00',
    status: 'Approved',
  },
   {
    id: '12',
    type: 'fee',
    title: 'Fee',
    date: '07-04-25 09:52 PM',
    amount: '- 10.00',
    status: 'Approved',
  },
  {
    id: '13',
    type: 'deposit_request_failed',
    title: 'Deposit',
    date: '01-04-25 07:08 PM',
    amount: '+ 10.00',
    status: 'Failed',
  },
];
